export const HEARTBEAT_INTERVAL = 5_000;
export const HEARTBEAT_GAP = 30_000;
export const RESPONSIVENESS_TIMEOUT = 1000;
export const OFFLINE_TIMEOUT = 5000;
export const REQUEST_COUNTER_LIMIT = Number.MAX_SAFE_INTEGER / 2;

export const CODES = {
	NORMAL: 1000,
	PROTOCOL_ERROR: 1002,
	ABNORMAL: 1006,
	NO_HEARTBEAT: 3000,
	OFFLINE: 3001,
	MANUAL: 3500,
	REOPEN: 4000
} as const;

export const NON_RECONNECTABLE_CODES = [
	CODES.PROTOCOL_ERROR,
	CODES.MANUAL,
	CODES.REOPEN
];

export const REQUEST_HEADERS = {
	REQUEST: "~r-q",
	RESPONSE: "~r-s"
};
